name = "Strata"
version = "0.1.0"
defaultTargets = ["Strata", "StrataMain", "StrataVerify", "StrataToCBMC"]
testDriver = "StrataTest"

[[lean_lib]]
name = "Strata"

[[lean_exe]]
name = "strata"
root = "StrataMain"

[[lean_lib]]
name = "StrataExamples"
globs = ["Examples.Lean.+"]

[[lean_lib]]
name = "StrataTest"
globs = ["StrataTest.+"]

[[lean_exe]]
name = "StrataVerify"

[[lean_exe]]
name = "StrataToCBMC"

[[require]]
name = "smt"
git = "https://github.com/abdoo8080/lean-smt"
rev = "meta-smt"
